## Important note:
## All paths defined in this configuration file must be either absolute or relative to the 
## location of the Snakefile!

## Paths to DNA fasta file (just the folder, not the file)
##--------------------------------------------------------------------------------------------
genome: /home/Shared_taupo/data/annotation/Human/Ensembl_GRCh37.97/genome/
##--------------------------------------------------------------------------------------------


## Information about the experiment
##--------------------------------------------------------------------------------------------

## Path to metadata text file. This file must contain at least the following columns:
## names: the sample identifiers = the names of the FASTQ files (excluding the _R1/R2.fastq.gz part)
## type: either SE or PE, indicating whether the sample was analyzed 
## via single-end or paired-end sequencing.

metatxt: metadata_healthy.txt
#or metatxt: metadata_lesions.txt

## Variables used for model fitting
## design: design formula for use with edgeR, camera and DRIMSeq. Must be a string 
## of the form "~ <predictors>"
## contrast: (comma-separated if multiple) list of contrasts to estimate in edgeR_dge.Rmd
#design: "~ 0 + celline"
#contrast: cellineN61311-cellineN052611,cellineN052611-cellineN61311

## The maximal number of cores to use for FastQC, Bismark
## Note that the actual number of cores available to Snakemake is determined by
## the --cores argument when it is invoked.
ncores: 2
##---------------------------------------------------------------------------------------------


## Path to a folder containing gzipped fastq files, and the file suffix (typically, either fastq or fq). 
## If you have paired-end fastq files, you also need to define the extension distinguishing the two read files. 
## More precisely, ARMOR assumes that paired-end fastq files are named 
## <sample-name>_<fqext1>.<fqsuffix>.gz and <sample-name>_<fqext2>.<fqsuffix>.gz.
## Single-end fastq files are supposed to be named 
## <sample-name>.<fqsuffix>.gz.
##---------------------------------------------------------------------------------------------
FASTQ: /home/Shared_s3it/sorjuela/serrated_BS_FASTQs
#FASTQ: /home/Shared_s3it/sorjuela/healthyfems_BS_FASTQs
fqext1: R1
fqext2: R2
fqsuffix: fastq
##---------------------------------------------------------------------------------------------


## Path to a folder that will store the output generated by the workflow. 
## Additional subfolders of this folder will be generated by the workflow. 
## To put output in the current directory, set output to ".".
##---------------------------------------------------------------------------------------------
output: /home/Shared_s3it/sorjuela/serrated_outputs
#output: /home/Shared_s3it/sorjuela/healthyfems_outputs
##---------------------------------------------------------------------------------------------

## Conditional conda rules
##---------------------------------------------------------------------------------------------
## Should read trimming be performed? Set
## to False if the step is not required.
run_trimming: True

##---------------------------------------------------------------------------------------------
