---
title: "3D MDS Age Samples"
author: "Stephany Orjuela"
date: "13/12/2019"
output: html_document
---

```{r setup, include=FALSE}

#run from console
#rmarkdown::render("scripts/3D_MDS_age.Rmd")

knitr::opts_chunk$set(echo = TRUE)

library(bsseq)
library(rgl)
load("~/age_females_meth/data/rdata/bsseq_age_filt.RData")
```


```{r, echo=FALSE, include = FALSE}
#Get Cov and meth
gr <- rowRanges(bismarkBSseq)
cov <- getCoverage(bismarkBSseq, type = "Cov")
meth <- getCoverage(bismarkBSseq, type = "M")

meth_vals <- meth /cov
colnames(meth_vals) <- colData(bismarkBSseq)$names
mcols(gr) <- meth_vals

bismarkBSseq$lesion <- paste0(bismarkBSseq$segment, "_", bismarkBSseq$age_group)

#Make windows
cl <- bumphunter::clusterMaker(seqnames(bismarkBSseq), start(bismarkBSseq))

gr$DMR <- cl

#use plyranges
gr_dmr <- gr %>% 
  group_by(DMR) %>% 
  summarise_at(
    colnames(meth_vals), mean, na.rm=TRUE) %>%
  as.matrix()
 
#Transform
methsTR <- asin(2*gr_dmr[,-1]-1)
m3 <- limma::plotMDS(methsTR, dim.plot=c(1,3), top = 10000, labels = colnames(meth_vals))

```

Blue: cecum_old  
Green: cecum_young  
Yellow: sigmoid_old     
Brown: sigmoid_young   

```{r, echo=FALSE}
myColor <- RColorBrewer::brewer.pal(8, "Set1")[c(2,3,6,7)]
m3cmds <- m3$cmdscale.out
par3d(cex=1)
plot3d(x = m3cmds[,1], y = m3cmds[,2], z = m3cmds[,3], xlab = "1", ylab = "2", zlab = "3", 
       col = myColor[as.factor(bismarkBSseq$lesion)], type="p", size=10)
# text3d(x = m3cmds[,1], y = m3cmds[,2], z = m3cmds[,3], cex = 0.8, 
#        font = 1, text = colnames(meth_vals), adj = 0.5, family="sans") 

subid <- currentSubscene3d()
rglwidget(elementId="3DMDS")
```